import React from "react";

export default function Legal({ legalSection, setRoute, setLegalSection }) {
  const navigateTo = (sec) => {
    setLegalSection(sec);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <div className="page-wrapper legal-page section-padding">
      <div className="container">
        <div className="legal-layout">
          {/* Sidebar navigation */}
          <aside className="legal-sidebar">
            <h4 className="sidebar-heading">LEGAL LEDGER</h4>
            <div className="sidebar-links">
              <button
                onClick={() => navigateTo("privacy")}
                className={`sidebar-btn ${legalSection === "privacy" ? "active" : ""}`}
              >
                Privacy Policy
              </button>
              <button
                onClick={() => navigateTo("terms")}
                className={`sidebar-btn ${legalSection === "terms" ? "active" : ""}`}
              >
                Terms of Service
              </button>
              <button
                onClick={() => navigateTo("shipping")}
                className={`sidebar-btn ${legalSection === "shipping" ? "active" : ""}`}
              >
                Shipping & Lead Times
              </button>
              <button
                onClick={() => navigateTo("returns")}
                className={`sidebar-btn ${legalSection === "returns" ? "active" : ""}`}
              >
                Returns & Claims
              </button>
            </div>
            
            <button
              onClick={() => { setRoute("home"); window.scrollTo({ top: 0, behavior: "smooth" }); }}
              className="btn btn-outline btn-sm btn-full m-top-2"
            >
              RETURN TO HOME
            </button>
          </aside>

          {/* Policy content */}
          <main className="legal-content-body fade-in">
            {legalSection === "privacy" && (
              <>
                <h1>PRIVACY POLICY</h1>
                <p className="policy-date">Last Updated: July 6, 2026</p>
                <p>
                  SOL Manufacturing & Packaging ("SOL", "we", "us", or "our") operates the website and contract portal. This page informs you of our policies regarding the collection, use, and disclosure of personal data and business credentials when you interact with our B2B forms.
                </p>
                <h3>1. Corporate Data Collection</h3>
                <p>
                  Because SOL operates exclusively as a B2B supplier, we collect corporate credentials including company name, state-issued operational licenses, corporate shipping destinations, and representative details. This data is used solely to verify credentials prior to shipping sample kits or generating contract manufacturing agreements.
                </p>
                <h3>2. Information Security</h3>
                <p>
                  We implement robust industrial database protections to ensure corporate data and uploaded designs or logos are stored in isolated directories. Uploaded branding files are destroyed from local server caches within 90 days of contract expiration or inquiry resolution.
                </p>
                <h3>3. Third-Party Disclosures</h3>
                <p>
                  We do not sell, rent, or lease corporate customer lists to third parties. Your company data will only be shared with licensed freight forwarding partners for customs clearance and direct delivery.
                </p>
              </>
            )}

            {legalSection === "terms" && (
              <>
                <h1>TERMS OF SERVICE</h1>
                <p className="policy-date">Last Updated: July 6, 2026</p>
                <p>
                  Please read these Terms of Service ("Terms") carefully before submitting a Request for Quotation (RFQ) or executing a contract manufacturing order with SOL Manufacturing & Packaging.
                </p>
                <h3>1. B2B Representations & Licensing</h3>
                <p>
                  SOL supplies empty pre-rolled paper cones and custom packaging solutions. We do not manufacture or distribute products containing botanicals or controlled substances. By purchasing from SOL, you represent that your company operates in full compliance with local state and federal laws and holds all necessary business licenses.
                </p>
                <h3>2. Wholesale Pricing & MOQs</h3>
                <p>
                  Wholesale estimates generated by our online calculators are simulations. Official contracts are issued exclusively by an authorized Account Director. Minimum order quantities (MOQs) are strictly enforced and cannot be waived.
                </p>
                <h3>3. Intellectual Property</h3>
                <p>
                  You retain all copyrights and trademark ownership of logos, branding designs, and watermarks submitted for custom printing. You represent that you have full legal rights to use any logos uploaded to SOL systems, and agree to indemnify SOL against any copyright claims.
                </p>
              </>
            )}

            {legalSection === "shipping" && (
              <>
                <h1>SHIPPING & LEAD TIMES</h1>
                <p className="policy-date">Last Updated: July 6, 2026</p>
                <p>
                  Please review our shipping policies, transit networks, and estimated manufacturing lead times.
                </p>
                <h3>1. Regional Hub Fulfillment</h3>
                <p>
                  Standard, unbranded bulk inventory (cases of 1,000 to 10,000 cones) are dispatched directly from our Los Angeles, CA or Rotterdam, NL hubs. In-stock orders ship within 1-2 business days.
                </p>
                <h3>2. Custom Order Lead Times</h3>
                <p>
                  Orders requiring custom logo printing, paper watermarking, or custom packaging fabrication involve a 4 to 6 week lead time. This timeframe includes:
                </p>
                <ul>
                  <li>Pre-production digital proofing and alignment (3-5 days)</li>
                  <li>Machinery alignment and custom rolling run (2-3 weeks)</li>
                  <li>Humidity calibration, QA cameras, and foil hermetic packing (3-5 days)</li>
                  <li>Ocean/Air freight to regional hub and customs clearance (10-15 days)</li>
                </ul>
                <h3>3. Custom Duties & Brokerage</h3>
                <p>
                  All custom contracts are shipped under DDP (Delivered Duty Paid) or FOB (Free On Board) rules depending on customer preference. For DDP orders, SOL handles all import filings, tariffs, and customs clearances.
                </p>
              </>
            )}

            {legalSection === "returns" && (
              <>
                <h1>RETURNS & CLAIMS</h1>
                <p className="policy-date">Last Updated: July 6, 2026</p>
                <p>
                  Review our quality guarantee, damage claims, and return authorization procedures.
                </p>
                <h3>1. Quality Variance Guarantee</h3>
                <p>
                  SOL operates under ISO 9001:2015 QA systems. If a custom cone run exhibits a dimensional deviance greater than 0.2mm (taper width) or has a seam glue failure rate exceeding 0.5%, we will issue a full remake of the defective run or credit your account.
                </p>
                <h3>2. Transit Damage & Claims</h3>
                <p>
                  Pre-rolled cones are delicate structures. If cases are crushed during transport, claims must be logged within 7 business days of delivery. Photos of the damaged outer crate and affected inner foil bags must be sent to compliance@solmanufacturing.com.
                </p>
                <h3>3. Custom Orders Refund Policy</h3>
                <p>
                  Because custom-printed pre-rolls and custom packaging are manufactured to unique company specifications, these orders are non-refundable once printing begins.
                </p>
              </>
            )}
          </main>
        </div>
      </div>
    </div>
  );
}
